#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

die() {
    echo '-------------------------' 1>&2
    echo 'pre-commit check failure' 1>&2
    echo '-------------------------' 1>&2
    echo "$@" 1>&2

    if [ -f /tmp/capp_lint.tmp ]; then
        rm -f /tmp/capp_lint.tmp
    fi

    exit 1
}

#-----------------------------------------------------------------------------
# Check for committer identity.
advice='
Use the commands:
    git config user.name '\''Firstname Lastname'\''
    git config user.email '\''you@yourdomain.com'\''
to introduce yourself to Git before committing.'

# Ensure name and email are available.
git config --get user.name > /dev/null &&
git config --get user.email > /dev/null ||
die 'Your Identity not configured!' "$advice"

# Validate the name and email.
git config --get user.name | grep ' ' > /dev/null ||
die 'Please set user.name to your Real Name (First letter Capital in Firstname and Lastname with a space), not a userid.' "$advice"

git config --get user.name | grep ^[A-Z]  > /dev/null || 
die 'Please set user.name as Firstname Lastname (First letter capital in Firstname)' "$advice"

git config --get user.name | cut -d ' ' -f 2 | grep ^[A-Z] > /dev/null ||
die 'Please set user.name as Firstname Lastname (First letter capital in Lastname)' "$advice"

git config --get user.email | grep '^[^@]*@[^@]*$' > /dev/null ||
die 'Please set user.email to an email address (userid@validdomain.com).' "$advice"

# Check content that will be added by this commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi


# Reject word if a specific word is found in file
#echo "Dear User" >&2
#if git diff --cached | grep '^\+' | grep -q 'Dilip'; then
#       echo "ERROR: cant commit word Dilip" >&2
#        exit 1 #reject
#fi
#exit 0 #accept


# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

